{
 "title": "Netcool Event Management",
 "description": "Event monitoring data extracted from ObjectServer alerts.status",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node", "query": "prom_custom_exporter" },
   { "name": "subsystem", "query": "prom_custom_exporter" },
   { "name": "metric", "query": "prom_custom_exporter" }
  ]
 },
 "panels": [
  {
   "title": "Event rate per minute",
   "type": "singlestat",
   "description": "rate of total event numbers per minute",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "irate(prom_custom_exporter{metric=\"total_evts_all\"}[1m])",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Events by State (I2P)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "prom_custom_exporter{metric=~\"total_evts_.*\", subsystem=~\".*i2p.*\"}",
     "legendFormat": "{{ metric }}"
    }
   ]
  },
  {
   "title": "Events by State (TS2)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "prom_custom_exporter{metric=~\"total_evts_.*\", subsystem=~\".*ts2.*\"}",
     "legendFormat": "{{ metric }}"
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(prom_custom_exporter{metric=~\"total_evts_.*\"})"
    }
   ]
  },
  {
   "title": "Process Failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "prom_custom_exporter{metric=\"zproc_failed\"}"
    }
   ]
  },
  {
   "title": "Unprocessed Events",
   "type": "singlestat",
   "description": "Current number of events not yet processed",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "prom_custom_exporter{metric=\"zproc_unproc\"}"
    }
   ]
  },
  {
   "title": "Primary ObjectServer CPU Busy",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"yourserverhostname\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"yourserverhostname\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"yourserverhostname\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Primary ObjectServer Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"yourserverhostname\"} * 100) / node_memory_MemTotal_bytes{instance=~\"yourserverhostname\"})"
    }
   ]
  },
  {
   "title": "Primary ObjectServer Root FS Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"yourserverhostname\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"yourserverhostname\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Processes by State",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prom_custom_exporter{metric=\"zproc_inprog\"}",
     "legendFormat": "{{metric}}"
    },
    {
     "expr": "prom_custom_exporter{metric=\"zproc_failed\"}",
     "legendFormat": "{{metric}}"
    },
    {
     "expr": "prom_custom_exporter{metric=\"zproc_unproc\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Ticket by State",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prom_custom_exporter{metric=\"ztkt_inprog\"}",
     "legendFormat": "{{metric}}"
    },
    {
     "expr": "prom_custom_exporter{metric=\"ztkt_failed\"}",
     "legendFormat": "{{metric}}"
    },
    {
     "expr": "prom_custom_exporter{metric=\"ztkt_retry\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  }
 ]
}